/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import com.toedter.calendar.JDateChooser;
import java.util.Calendar;
import java.util.Date;
import payroll.libraries.Common;

/**
 *
 * @author ho
 */
public class EditTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form EditTransaksi
     */
    public EditTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workerRecordID = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTransactionDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTransactionDate = new com.toedter.calendar.JDateChooser();
        cbxTransactionClients = new javax.swing.JComboBox();
        txtTransactionWeight = new javax.swing.JTextField();
        txtTransactionPricePerTon = new javax.swing.JTextField();
        txtTransactionTotalReceived = new javax.swing.JTextField();
        txtTransactionWages = new javax.swing.JTextField();
        txtTransactionSalary = new javax.swing.JTextField();
        txtTransactionBalance = new javax.swing.JTextField();
        txtTransactionCalculate = new javax.swing.JTextField();
        workerRecordID1 = new javax.swing.JTextField();
        txtTransactionPayPerPerson = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cancelEditTransaksi = new javax.swing.JButton();

        workerRecordID.setEditable(false);
        workerRecordID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Rekod ID");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Kod & Nama Pelanggan");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Berat KG");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Harga Diterima Seton");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah Diterima");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Upah Kerja");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Jumlah Gaji");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Jumlah Baki");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Kiraan Asing");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Upah Perseorangan");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Keterangan");

        txtTransactionDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tarikh");

        txtTransactionDate.setDate(Calendar.getInstance().getTime());
        txtTransactionDate.setDateFormatString("dd/MM/yyyy");
        txtTransactionDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTransactionDatedateChange(evt);
            }
        });

        cbxTransactionClients.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtTransactionWeight.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransactionWeightActionPerformed(evt);
            }
        });
        txtTransactionWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTransactionWeightcalculateTransaction(evt);
            }
        });

        txtTransactionPricePerTon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionPricePerTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransactionPricePerTonActionPerformed(evt);
            }
        });
        txtTransactionPricePerTon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTransactionPricePerToncalculateTransaction(evt);
            }
        });

        txtTransactionTotalReceived.setEditable(false);
        txtTransactionTotalReceived.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionTotalReceived.setFocusable(false);

        txtTransactionWages.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionWages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransactionWagesActionPerformed(evt);
            }
        });
        txtTransactionWages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTransactionWagescalculateTransaction(evt);
            }
        });

        txtTransactionSalary.setEditable(false);
        txtTransactionSalary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionSalary.setFocusable(false);

        txtTransactionBalance.setEditable(false);
        txtTransactionBalance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionBalance.setFocusable(false);

        txtTransactionCalculate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionCalculate.setText("0");
        txtTransactionCalculate.setToolTipText("");
        txtTransactionCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransactionCalculateActionPerformed(evt);
            }
        });
        txtTransactionCalculate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTransactionCalculatecalculateTransaction(evt);
            }
        });

        workerRecordID1.setEditable(false);
        workerRecordID1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtTransactionPayPerPerson.setEditable(false);
        txtTransactionPayPerPerson.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTransactionPayPerPerson.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Ubah");
        jButton1.setActionCommand("saveUbahTransaksi");

        cancelEditTransaksi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelEditTransaksi.setText("Batal");
        cancelEditTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(cancelEditTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cancelEditTransaksi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("saveUbahTransaksi");
        cancelEditTransaksi.getAccessibleContext().setAccessibleName("cancelEditTransaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTransactionWeight, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTransactionClients, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTransactionDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(workerRecordID1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTransactionPricePerTon, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTransactionTotalReceived)
                                    .addComponent(txtTransactionWages))))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTransactionSalary)
                                    .addComponent(txtTransactionCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(txtTransactionBalance, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTransactionPayPerPerson, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTransactionDescription, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(workerRecordID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTransactionClients, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionPricePerTon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionTotalReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionWages, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransactionPayPerPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTransactionDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTransactionDatedateChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTransactionDatedateChange
        if (evt.getNewValue() instanceof Date) {
            Date date = (Date) evt.getNewValue();

            Calendar calendar = Calendar.getInstance();
            calendar.setTime(date);

            if (calendar.get(Calendar.YEAR) <= 2000) {
                int year = calendar.get(Calendar.YEAR) + 2000;
                calendar.set(Calendar.YEAR, year);
            }

            JDateChooser dateChooser = (JDateChooser) evt.getSource();
            dateChooser.setDate(calendar.getTime());
        }
    }//GEN-LAST:event_txtTransactionDatedateChange

    private void txtTransactionWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransactionWeightActionPerformed
        if (txtTransactionWeight.getText().isEmpty()) {
            txtTransactionWeight.setText("0.00");
        }
        calculateTransaction(null);
    }//GEN-LAST:event_txtTransactionWeightActionPerformed

private void calculateTransaction(java.awt.event.KeyEvent evt) {                                      
        if (txtTransactionPricePerTon.getText().isEmpty() || 
                txtTransactionWeight.getText().isEmpty() || 
                !Common.isDouble(txtTransactionPricePerTon.getText()) || 
                !Common.isDouble(txtTransactionWeight.getText())) {
            return;
        }

        double kiraanAsing = 0.0;
        if (Common.isDouble(txtTransactionCalculate.getText())) {
            kiraanAsing = Double.parseDouble(txtTransactionCalculate.getText());
        }

        double weight = Double.parseDouble(txtTransactionWeight.getText()), 
                price_per_ton = 0.0;

        if (!txtTransactionPricePerTon.getText().isEmpty() && 
                Common.isDouble(txtTransactionPricePerTon.getText())) {
            price_per_ton = Double.parseDouble(txtTransactionPricePerTon.getText());
        }

        double total = ((weight / 1000) * price_per_ton) + (kiraanAsing * price_per_ton);

        txtTransactionTotalReceived.setText(Common.currency(total));

        if (txtTransactionWages.getText().isEmpty() || 
                !Common.isDouble(txtTransactionWages.getText())) {
            return;
        }

        double wages = 0.0, wages_tax = 0.0, salary = 0.0, salary_tax;

        if (!txtTransactionWages.getText().isEmpty() && 
                Common.isDouble(txtTransactionWages.getText())) {
            wages = Double.parseDouble(txtTransactionWages.getText());
        }

        salary = ((weight / 1000) * wages) + (kiraanAsing * wages);
        salary_tax = ((weight / 1000) * wages_tax) + (kiraanAsing * wages_tax);
        txtTransactionSalary.setText(Common.currency(salary));

        txtTransactionBalance.setText(Common.currency(total - salary));

        int worker_count = 0;
//        int row = tblTransactionInvolvedWorkers.getRowCount();
//        for (int i = 0; i < row; i++) {
//            if (Boolean.parseBoolean(tblTransactionInvolvedWorkers.getValueAt(i, 0).toString()) == true) {
//                worker_count++;
//            }
//        }

        worker_count = worker_count > 0 ? worker_count : 1;
        txtTransactionPayPerPerson.setText(Common.currency(salary / worker_count));

    }        
    
    private void txtTransactionWeightcalculateTransaction(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransactionWeightcalculateTransaction
        if (txtTransactionPricePerTon.getText().isEmpty() || 
                txtTransactionWeight.getText().isEmpty() || 
                !Common.isDouble(txtTransactionPricePerTon.getText()) || 
                !Common.isDouble(txtTransactionWeight.getText())) {
            return;
        }

        double kiraanAsing = 0.0;
        if (Common.isDouble(txtTransactionCalculate.getText())) {
            kiraanAsing = Double.parseDouble(txtTransactionCalculate.getText());
        }

        double weight = Double.parseDouble(txtTransactionWeight.getText()), 
                price_per_ton = 0.0;

        if (!txtTransactionPricePerTon.getText().isEmpty() && 
                Common.isDouble(txtTransactionPricePerTon.getText())) {
            price_per_ton = Double.parseDouble(txtTransactionPricePerTon.getText());
        }

        double total = ((weight / 1000) * price_per_ton) + (kiraanAsing * price_per_ton);

        txtTransactionTotalReceived.setText(Common.currency(total));

        if (txtTransactionWages.getText().isEmpty() || 
                !Common.isDouble(txtTransactionWages.getText())) {
            return;
        }

        double wages = 0.0, wages_tax = 0.0, salary = 0.0, salary_tax;

        if (!txtTransactionWages.getText().isEmpty() && 
                Common.isDouble(txtTransactionWages.getText())) {
            wages = Double.parseDouble(txtTransactionWages.getText());
        }

        salary = ((weight / 1000) * wages) + (kiraanAsing * wages);
        salary_tax = ((weight / 1000) * wages_tax) + (kiraanAsing * wages_tax);
        txtTransactionSalary.setText(Common.currency(salary));

        txtTransactionBalance.setText(Common.currency(total - salary));

        int worker_count = 0;
//        int row = tblTransactionInvolvedWorkers.getRowCount();
//        for (int i = 0; i < row; i++) {
//            if (Boolean.parseBoolean(tblTransactionInvolvedWorkers.getValueAt(i, 0).toString()) == true) {
//                worker_count++;
//            }
//        }

        worker_count = worker_count > 0 ? worker_count : 1;
        txtTransactionPayPerPerson.setText(Common.currency(salary / worker_count));
    }//GEN-LAST:event_txtTransactionWeightcalculateTransaction

    private void txtTransactionPricePerTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransactionPricePerTonActionPerformed
        if (txtTransactionPricePerTon.getText().isEmpty()) {
            txtTransactionPricePerTon.setText("0.00");
        }
        calculateTransaction(null);
    }//GEN-LAST:event_txtTransactionPricePerTonActionPerformed

    private void txtTransactionPricePerToncalculateTransaction(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransactionPricePerToncalculateTransaction
        if (txtTransactionPricePerTon.getText().isEmpty() || 
                txtTransactionWeight.getText().isEmpty() || 
                !Common.isDouble(txtTransactionPricePerTon.getText()) || 
                !Common.isDouble(txtTransactionWeight.getText())) {
            return;
        }

        double kiraanAsing = 0.0;
        if (Common.isDouble(txtTransactionCalculate.getText())) {
            kiraanAsing = Double.parseDouble(txtTransactionCalculate.getText());
        }

        double weight = Double.parseDouble(txtTransactionWeight.getText()), 
                price_per_ton = 0.0;

        if (!txtTransactionPricePerTon.getText().isEmpty() && 
                Common.isDouble(txtTransactionPricePerTon.getText())) {
            price_per_ton = Double.parseDouble(txtTransactionPricePerTon.getText());
        }

        double total = ((weight / 1000) * price_per_ton) + (kiraanAsing * price_per_ton);

        txtTransactionTotalReceived.setText(Common.currency(total));

        if (txtTransactionWages.getText().isEmpty() || 
                !Common.isDouble(txtTransactionWages.getText())) {
            return;
        }

        double wages = 0.0, wages_tax = 0.0, salary = 0.0, salary_tax;

        if (!txtTransactionWages.getText().isEmpty() && 
                Common.isDouble(txtTransactionWages.getText())) {
            wages = Double.parseDouble(txtTransactionWages.getText());
        }

        salary = ((weight / 1000) * wages) + (kiraanAsing * wages);
        salary_tax = ((weight / 1000) * wages_tax) + (kiraanAsing * wages_tax);
        txtTransactionSalary.setText(Common.currency(salary));

        txtTransactionBalance.setText(Common.currency(total - salary));

        int worker_count = 0;
//        int row = tblTransactionInvolvedWorkers.getRowCount();
//        for (int i = 0; i < row; i++) {
//            if (Boolean.parseBoolean(tblTransactionInvolvedWorkers.getValueAt(i, 
//                    0).toString()) == true) {
//                worker_count++;
//            }
//        }

        worker_count = worker_count > 0 ? worker_count : 1;
        txtTransactionPayPerPerson.setText(Common.currency(salary / worker_count));
    }//GEN-LAST:event_txtTransactionPricePerToncalculateTransaction

    private void txtTransactionWagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransactionWagesActionPerformed
        if (txtTransactionWages.getText().isEmpty()) {
            txtTransactionWages.setText("0.00");
        }
        calculateTransaction(null);
    }//GEN-LAST:event_txtTransactionWagesActionPerformed

    private void txtTransactionWagescalculateTransaction(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransactionWagescalculateTransaction
        if (txtTransactionPricePerTon.getText().isEmpty() || 
                txtTransactionWeight.getText().isEmpty() || 
                !Common.isDouble(txtTransactionPricePerTon.getText()) || 
                !Common.isDouble(txtTransactionWeight.getText())) {
            return;
        }

        double kiraanAsing = 0.0;
        if (Common.isDouble(txtTransactionCalculate.getText())) {
            kiraanAsing = Double.parseDouble(txtTransactionCalculate.getText());
        }

        double weight = Double.parseDouble(txtTransactionWeight.getText()), 
                price_per_ton = 0.0;

        if (!txtTransactionPricePerTon.getText().isEmpty() && 
                Common.isDouble(txtTransactionPricePerTon.getText())) {
            price_per_ton = Double.parseDouble(txtTransactionPricePerTon.getText());
        }

        double total = ((weight / 1000) * price_per_ton) + (kiraanAsing * price_per_ton);

        txtTransactionTotalReceived.setText(Common.currency(total));

        if (txtTransactionWages.getText().isEmpty() || 
                !Common.isDouble(txtTransactionWages.getText())) {
            return;
        }

        double wages = 0.0, wages_tax = 0.0, salary = 0.0, salary_tax;

        if (!txtTransactionWages.getText().isEmpty() && 
                Common.isDouble(txtTransactionWages.getText())) {
            wages = Double.parseDouble(txtTransactionWages.getText());
        }

        salary = ((weight / 1000) * wages) + (kiraanAsing * wages);
        salary_tax = ((weight / 1000) * wages_tax) + (kiraanAsing * wages_tax);
        txtTransactionSalary.setText(Common.currency(salary));

        txtTransactionBalance.setText(Common.currency(total - salary));

        int worker_count = 0;
//        int row = tblTransactionInvolvedWorkers.getRowCount();
//        for (int i = 0; i < row; i++) {
//            if (Boolean.parseBoolean(tblTransactionInvolvedWorkers.getValueAt(i, 
//                    0).toString()) == true) {
//                worker_count++;
//            }
//        }

        worker_count = worker_count > 0 ? worker_count : 1;
        txtTransactionPayPerPerson.setText(Common.currency(salary / worker_count));
    }//GEN-LAST:event_txtTransactionWagescalculateTransaction

    private void txtTransactionCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransactionCalculateActionPerformed
        if (txtTransactionCalculate.getText().isEmpty()) {
            txtTransactionCalculate.setText("0.00");
        }
        calculateTransaction(null);
    }//GEN-LAST:event_txtTransactionCalculateActionPerformed

    private void txtTransactionCalculatecalculateTransaction(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransactionCalculatecalculateTransaction
        if (txtTransactionPricePerTon.getText().isEmpty() || 
                txtTransactionWeight.getText().isEmpty() || 
                !Common.isDouble(txtTransactionPricePerTon.getText()) || 
                !Common.isDouble(txtTransactionWeight.getText())) {
            return;
        }

        double kiraanAsing = 0.0;
        if (Common.isDouble(txtTransactionCalculate.getText())) {
            kiraanAsing = Double.parseDouble(txtTransactionCalculate.getText());
        }

        double weight = Double.parseDouble(txtTransactionWeight.getText()), 
                price_per_ton = 0.0;

        if (!txtTransactionPricePerTon.getText().isEmpty() && 
                Common.isDouble(txtTransactionPricePerTon.getText())) {
            price_per_ton = Double.parseDouble(txtTransactionPricePerTon.getText());
        }

        double total = ((weight / 1000) * price_per_ton) + (kiraanAsing * price_per_ton);

        txtTransactionTotalReceived.setText(Common.currency(total));

        if (txtTransactionWages.getText().isEmpty() || 
                !Common.isDouble(txtTransactionWages.getText())) {
            return;
        }

        double wages = 0.0, wages_tax = 0.0, salary = 0.0, salary_tax;

        if (!txtTransactionWages.getText().isEmpty() && 
                Common.isDouble(txtTransactionWages.getText())) {
            wages = Double.parseDouble(txtTransactionWages.getText());
        }

        salary = ((weight / 1000) * wages) + (kiraanAsing * wages);
        salary_tax = ((weight / 1000) * wages_tax) + (kiraanAsing * wages_tax);
        txtTransactionSalary.setText(Common.currency(salary));

        txtTransactionBalance.setText(Common.currency(total - salary));

        int worker_count = 0;
//        int row = tblTransactionInvolvedWorkers.getRowCount();
//        for (int i = 0; i < row; i++) {
//            if (Boolean.parseBoolean(tblTransactionInvolvedWorkers.getValueAt(i, 
//                    0).toString()) == true) {
//                worker_count++;
//            }
//        }

        worker_count = worker_count > 0 ? worker_count : 1;
        txtTransactionPayPerPerson.setText(Common.currency(salary / worker_count));
    }//GEN-LAST:event_txtTransactionCalculatecalculateTransaction

    private void cancelEditTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditTransaksiActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelEditTransaksiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelEditTransaksi;
    private javax.swing.JComboBox cbxTransactionClients;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtTransactionBalance;
    private javax.swing.JTextField txtTransactionCalculate;
    private com.toedter.calendar.JDateChooser txtTransactionDate;
    private javax.swing.JTextField txtTransactionDescription;
    private javax.swing.JTextField txtTransactionPayPerPerson;
    private javax.swing.JTextField txtTransactionPricePerTon;
    private javax.swing.JTextField txtTransactionSalary;
    private javax.swing.JTextField txtTransactionTotalReceived;
    private javax.swing.JTextField txtTransactionWages;
    private javax.swing.JTextField txtTransactionWeight;
    private javax.swing.JTextField workerRecordID;
    private javax.swing.JTextField workerRecordID1;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
