/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WorkerReportFrame.java
 *
 * Created on Aug 12, 2012, 4:54:49 AM
 */

package payroll;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import payroll.libraries.Common;
import payroll.libraries.Database;

/**
 *
 * @author Edward
 */
public class WorkerReportFrame extends javax.swing.JFrame {

    private ResultSet results = null;
    private DefaultTableModel tableModel;

    public static final int FULL = 1;
    public static final int INCOME = 2;
    public static final int SAVING = 3;
    
    /** Creates new form WorkerReportFrame */
    public WorkerReportFrame(int type, String query) {
        initComponents();
        
        try {
            this.setExtendedState(this.MAXIMIZED_BOTH);
            this.setAlwaysOnTop(true);
            this.toFront();
            this.requestFocus();
            this.setAlwaysOnTop(false);
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }

        results = Database.instance().execute(query);
        
        if (type == FULL) {
            this.full_setup();
        } else if (type == INCOME) {
            this.monthly_income_setup();
        } else if (type == SAVING) {
            this.saving_setup();
        }
    }

    private void full_setup() {
        tableModel = new DefaultTableModel(
            new Object[][] {},
            new String[] {
                "Tempoh", "Gaji", "Pinjaman", "Baki", "Simpanan", "Bayaran", "Baki"
            }
        );
        tblReport.setModel(tableModel);

        try {
            double baki = 0.00;
            while (results.next()) {
                Object[] objects = new Object[] {
                    new String(Common.renderDisplayDate(new Date(results.getDate("date").getTime()))),
                    new String(),
                    new String(),
                    new String(),
                    new String(results.getBoolean("is_pay") ? "" : Common.currency(results.getDouble("amount") )),
                    new String(results.getBoolean("is_pay") ? Common.currency(results.getDouble("amount") ) : ""),
                    new String(results.getBoolean("is_pay") ? Common.currency(baki += (0 -results.getDouble("amount"))) : Common.currency(baki += results.getDouble("amount")))
                };

                tableModel.addRow(objects);
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    private void monthly_income_setup() {
        tableModel = new DefaultTableModel(
            new Object[][] {},
            new String[] {
                "Tempoh", "Gaji", "Pinjaman", "Baki"
            }
        );
        tblReport.setModel(tableModel);


        try {
            while (results.next()) {
                Object[] objects = new Object[] {
                    new String(Common.renderDisplayDate(new Date(results.getDate("date").getTime()))),
                    new String(),
                    new String(),
                    new String(),
                };

                tableModel.addRow(objects);
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    private void saving_setup() {
        tableModel = new DefaultTableModel(
            new Object[][] {},
            new String[] {
                "Tempoh", "Simpanan", "Bayaran", "Baki"
            }
        );
        tblReport.setModel(tableModel);

        try {
            double baki = 0.00;
            while (results.next()) {
                Object[] objects = new Object[] {
                    new String(Common.renderDisplayDate(new Date(results.getDate("date").getTime()))),
                    new String(results.getBoolean("is_pay") ? "" : Common.currency(results.getDouble("amount") )),
                    new String(results.getBoolean("is_pay") ? Common.currency(results.getDouble("amount") ) : ""),
                    new String(results.getBoolean("is_pay") ? Common.currency(baki += (0 -results.getDouble("amount"))) : Common.currency(baki += results.getDouble("amount")))
                };

                tableModel.addRow(objects);
            }
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1016)/2, (screenSize.height-638)/2, 1016, 638);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables

}
